import type { Member, Publication, NewsItem } from '@/types'

export const LAB_INFO = {
  name: 'FanLearn Lab',
  nameCn: '泛学习实验室',
  slogan: 'Learning that Generalizes. Intelligence that Endures.',
  university: '北京大学',
  department: '教育学院',
  description:
    'FanLearn Lab 专注于人工智能与教育融合研究，致力于探索学习的本质规律，开发面向未来的智能学习系统。',
  researchInterests: [
    '大语言模型',
    '教育数据挖掘',
    '学习分析',
    '智能辅导系统',
    '自然语言处理',
    '知识追踪',
  ],
  contactEmail: 'fanlearn@pku.edu.cn',
  location: '北京市海淀区颐和园路5号',
  foundedYear: 2020,
}

export const MOCK_MEMBERS: Member[] = [
  {
    id: '1',
    slug: 'fan-yizhou',
    name: '范逸洲',
    nameEn: 'Yizhou Fan',
    category: 'advisor',
    title: '副教授、博士生导师',
    isAdmin: true,
    avatarUrl: '/default-avatar.png',
    bio:
      '北京大学教育学院副教授，博士生导师。主要研究方向为人工智能与教育、学习分析、智能辅导系统。在 AIED、LAK、EDM、ACL、EMNLP 等国际顶级会议及 Computers & Education、Learning and Instruction 等权威期刊发表论文 40+ 篇。主持国家自然科学基金、北京市科技计划等多项课题。',
    researchInterests: ['大语言模型', '学习分析', '智能辅导系统'],
    email: 'fanyizhou@pku.edu.cn',
    googleScholarUrl: 'https://scholar.google.com/citations?user=PLACEHOLDER',
    hIndex: 18,
    citationCount: 1500,
    joinYear: 2020,
    isActive: true,
    aliases: ['Yizhou Fan', 'Fan Yizhou', 'Y. Fan', 'Fan Y.'],
  },
  {
    id: '2',
    slug: 'xia-mengyu',
    name: '夏梦雨',
    nameEn: 'Mengyu Xia',
    category: 'researcher',
    title: '博士研究生',
    avatarUrl: '/default-avatar.png',
    bio:
      '博士研究生，主要研究方向为大语言模型在教育场景中的应用与评估，聚焦于自动作文评阅与个性化学习反馈。在 ACL、EMNLP 等顶级 NLP 会议发表论文多篇。',
    researchInterests: ['大语言模型', '自动评测', '个性化学习'],
    email: 'xiamengyu@pku.edu.cn',
    githubUrl: 'https://github.com/placeholder',
    hIndex: 4,
    citationCount: 85,
    joinYear: 2022,
    isActive: true,
    aliases: ['Mengyu Xia', 'Xia Mengyu', 'M. Xia', 'Xia M.'],
  },
  {
    id: '3',
    slug: 'zhu-taolin',
    name: '朱桃林',
    nameEn: 'Taolin Zhu',
    category: 'researcher',
    title: '硕士研究生',
    avatarUrl: '/default-avatar.png',
    bio:
      '硕士研究生，研究方向为知识追踪与认知诊断建模，致力于利用深度学习方法精准刻画学生知识状态，为自适应学习系统提供支撑。',
    researchInterests: ['知识追踪', '认知诊断', '自适应学习'],
    email: 'zhutaolin@pku.edu.cn',
    hIndex: 2,
    citationCount: 28,
    joinYear: 2023,
    isActive: true,
    aliases: ['Taolin Zhu', 'Zhu Taolin', 'T. Zhu', 'Zhu T.'],
  },
  {
    id: '5',
    slug: 'ma-junyang',
    name: '马郡阳',
    nameEn: 'Junyang Ma',
    category: 'researcher',
    title: '硕士研究生',
    isAdmin: true,
    avatarUrl: '/default-avatar.png',
    bio: '北京大学信息管理系本科生，2026年9月起在北京大学教育学院攻读硕士学位。',
    researchInterests: [],
    joinYear: 2026,
    isActive: true,
    aliases: ['Junyang Ma', 'Ma Junyang', 'J. Ma', 'Ma J.'],
  },
  {
    id: '6',
    slug: 'member-a',
    name: '成员A',
    nameEn: 'Member A',
    category: 'advisor',
    title: '博士后',
    isAdmin: false,
    avatarUrl: '/default-avatar.png',
    bio: '课题组虚拟博士后成员，用于网站内容与管理流程演示。',
    researchInterests: ['人工智能与教育'],
    joinYear: 2024,
    isActive: true,
    aliases: ['Member A'],
  },
  {
    id: '7',
    slug: 'member-b',
    name: '成员B',
    nameEn: 'Member B',
    category: 'advisor',
    title: '博士后',
    isAdmin: false,
    avatarUrl: '/default-avatar.png',
    bio: '课题组虚拟博士后成员，用于网站内容与管理流程演示。',
    researchInterests: ['学习分析'],
    joinYear: 2024,
    isActive: true,
    aliases: ['Member B'],
  },
  {
    id: '8',
    slug: 'member-c',
    name: '成员C',
    nameEn: 'Member C',
    category: 'researcher',
    title: '博士研究生',
    isAdmin: false,
    avatarUrl: '/default-avatar.png',
    bio: '课题组虚拟博士研究生，用于网站内容与管理流程演示。',
    researchInterests: ['智能辅导系统'],
    joinYear: 2025,
    isActive: true,
    aliases: ['Member C'],
  },
  {
    id: '9',
    slug: 'member-d',
    name: '成员D',
    nameEn: 'Member D',
    category: 'researcher',
    title: '硕士研究生',
    isAdmin: false,
    avatarUrl: '/default-avatar.png',
    bio: '课题组虚拟硕士研究生，用于网站内容与管理流程演示。',
    researchInterests: ['教育数据挖掘'],
    joinYear: 2025,
    isActive: true,
    aliases: ['Member D'],
  },
  {
    id: '10',
    slug: 'member-e',
    name: '成员E',
    nameEn: 'Member E',
    category: 'alumni',
    title: '博士毕业生',
    isAdmin: false,
    avatarUrl: '/default-avatar.png',
    bio: '课题组虚拟博士毕业成员，用于网站内容与管理流程演示。',
    researchInterests: ['大语言模型'],
    joinYear: 2021,
    graduateYear: 2025,
    isActive: false,
    aliases: ['Member E'],
  },
  {
    id: '11',
    slug: 'member-f',
    name: '成员F',
    nameEn: 'Member F',
    category: 'alumni',
    title: '硕士毕业生',
    isAdmin: false,
    avatarUrl: '/default-avatar.png',
    bio: '课题组虚拟硕士毕业成员，用于网站内容与管理流程演示。',
    researchInterests: ['学习科学'],
    joinYear: 2022,
    graduateYear: 2025,
    isActive: false,
    aliases: ['Member F'],
  },
  {
    id: '12',
    slug: 'xu-jiaqi',
    name: '许家奇',
    nameEn: 'Jiaqi Xu',
    category: 'researcher',
    title: '博士研究生',
    isAdmin: false,
    avatarUrl: '/default-avatar.png',
    bio: '北京大学教育学院博士研究生，主要关注教育技术与人机协同学习方向。',
    researchInterests: ['教育技术', '人机协同学习'],
    joinYear: 2024,
    isActive: true,
    aliases: ['Jiaqi Xu', 'Xu Jiaqi', 'J. Xu', 'Xu J.'],
  },
  {
    id: '14',
    slug: 'li-zijian',
    name: '李子健',
    nameEn: 'Zijian Li',
    category: 'researcher',
    title: '博士研究生',
    isAdmin: false,
    avatarUrl: '/default-avatar.png',
    bio: '北京大学教育学院博士研究生，主要研究生成式 AI 对学习者元认知与自我调节学习的影响，以及学习分析中的大语言模型应用。',
    researchInterests: ['生成式 AI 与学习', '元认知与自我调节学习', '学习分析'],
    joinYear: 2023,
    isActive: true,
    aliases: ['Zijian Li', 'Li Zijian', 'Z. Li', 'Li Z.'],
  },
  {
    id: '13',
    slug: 'ma-ling',
    name: '马玲',
    nameEn: 'Ling Ma',
    category: 'researcher',
    title: '博士研究生',
    isAdmin: false,
    avatarUrl: '/default-avatar.png',
    bio: '曾在华东师范大学学习，2026年9月起在北京大学教育学院攻读博士学位。',
    researchInterests: [],
    joinYear: 2026,
    isActive: true,
    aliases: ['Ling Ma', 'Ma Ling'],
  },
  {
    id: '4',
    slug: 'tang-luzhen',
    name: '唐陆禛',
    nameEn: 'Luzhen Tang',
    category: 'alumni',
    title: '2026届硕士毕业生',
    avatarUrl: '/default-avatar.png',
    bio:
      '2026年硕士毕业。硕士期间主要研究在线学习平台中的学习行为分析与学业预警，在 LAK、EDM 等会议发表论文。',
    researchInterests: ['学习行为分析', '学业预警', '教育数据挖掘'],
    hIndex: 3,
    citationCount: 45,
    joinYear: 2021,
    graduateYear: 2026,
    isActive: false,
    aliases: ['Luzhen Tang', 'Tang Luzhen', 'L. Tang', 'Tang L.'],
  },
]

export const MOCK_PUBLICATIONS: Publication[] = [
  {
    id: 'real_zh_2024_academic_writing_book',
    title: '英文学术写作实战',
    authors: ['范逸洲', '童士敦', '毛君'],
    venue: '清华大学出版社',
    year: 2024,
    sourceUrl: 'https://read.douban.com/ebook/491172746/',
    language: 'zh',
    abstract:
      '本书从学术论文写作、编辑与教学经验出发，系统介绍英文学术写作的思维、结构、语言、常见误区和实践方法，为科研人员提供可操作的写作参考。',
    pubType: 'book',
    citationCount: 0,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['fan-yizhou'],
    tags: ['学术写作', '英文论文', '研究方法'],
    createdAt: '2024-05-01',
  },
  {
    id: '1',
    title: 'FeedbackGen: Automated Personalized Feedback Generation for Student Writing with Large Language Models',
    authors: ['Mengyu Xia', 'Yizhou Fan'],
    venue: 'ACL 2024',
    year: 2024,
    doi: '10.18653/v1/2024.acl-long.001',
    arxivId: '2401.00001',
    pdfUrl: 'https://arxiv.org/pdf/2401.00001',
    abstract:
      'We propose FeedbackGen, a large language model-based framework for generating personalized and actionable feedback on student essays. Our approach leverages rubric-aligned chain-of-thought prompting and a human preference alignment mechanism to produce feedback that is both accurate and pedagogically meaningful. Experiments on two large-scale datasets show that FeedbackGen outperforms previous methods by a significant margin and is preferred by teachers in blind evaluation.',
    pubType: 'conference',
    citationCount: 62,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['xia-mengyu', 'fan-yizhou'],
    tags: ['LLM', 'Feedback Generation', 'Writing Assessment'],
    createdAt: '2024-06-01',
  },
  {
    id: '2',
    title: 'Revisiting Knowledge Tracing: A Deep Contrastive Learning Approach with Temporal Attention',
    authors: ['Taolin Zhu', 'Yizhou Fan', 'Mengyu Xia'],
    venue: 'AIED 2024',
    year: 2024,
    arxivId: '2404.00002',
    pdfUrl: 'https://arxiv.org/pdf/2404.00002',
    abstract:
      'Knowledge tracing (KT) aims to model student knowledge states over time from their interaction sequences. We propose ContraKT, a contrastive learning framework for knowledge tracing that captures subtle distinctions between similar knowledge concepts through temporal self-supervised objectives. Our model achieves state-of-the-art results on four benchmark datasets while providing interpretable knowledge state representations.',
    pubType: 'conference',
    citationCount: 28,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['zhu-taolin', 'fan-yizhou', 'xia-mengyu'],
    tags: ['Knowledge Tracing', 'Contrastive Learning', 'Student Modeling'],
    createdAt: '2024-07-10',
  },
  {
    id: '3',
    title: 'Early Warning Systems for Student Academic Performance: A Survey and Benchmark',
    authors: ['Luzhen Tang', 'Yizhou Fan'],
    venue: 'LAK 2024',
    year: 2024,
    doi: '10.1145/3636555.3636904',
    pdfUrl: 'https://dl.acm.org/doi/10.1145/PLACEHOLDER',
    abstract:
      'Academic early warning systems are essential tools for identifying at-risk students and providing timely interventions. We conduct a comprehensive survey of existing approaches and introduce a unified benchmark for fair comparison. Our benchmark covers six datasets across different educational contexts and evaluates models on both predictive performance and interpretability, revealing significant gaps between current methods and practical requirements.',
    pubType: 'conference',
    citationCount: 41,
    isHighlight: false,
    status: 'published',
    source: 'auto_crawler',
    relatedMemberSlugs: ['tang-luzhen', 'fan-yizhou'],
    tags: ['Early Warning', 'Academic Performance', 'Survey'],
    createdAt: '2024-03-15',
  },
  {
    id: '4',
    title: 'Evaluating LLMs as Automated Essay Scoring Systems: Beyond Correlation with Human Raters',
    authors: ['Mengyu Xia', 'Yizhou Fan'],
    venue: 'EMNLP 2023',
    year: 2023,
    arxivId: '2310.00003',
    pdfUrl: 'https://arxiv.org/pdf/2310.00003',
    abstract:
      'Automated essay scoring (AES) has traditionally been evaluated by correlation with human rater scores. We argue this metric is insufficient and propose a multi-dimensional evaluation framework encompassing scoring accuracy, scoring consistency, robustness to adversarial inputs, and alignment with pedagogical criteria. We benchmark 12 LLMs under this framework, revealing that high correlation does not imply good holistic performance.',
    pubType: 'conference',
    citationCount: 78,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['xia-mengyu', 'fan-yizhou'],
    tags: ['AES', 'LLM Evaluation', 'NLP in Education'],
    createdAt: '2023-11-01',
  },
  {
    id: '5',
    title: 'Cognitive Diagnosis in Online Education: A Graph-Enhanced Neural Framework',
    authors: ['Taolin Zhu', 'Yizhou Fan'],
    venue: 'arXiv',
    year: 2024,
    arxivId: '2406.00004',
    pdfUrl: 'https://arxiv.org/pdf/2406.00004',
    abstract:
      'Cognitive diagnostic models (CDMs) estimate student proficiency on fine-grained knowledge attributes. We propose GCDN, a graph-enhanced cognitive diagnostic network that explicitly models the prerequisite relationships between knowledge concepts via graph neural networks. GCDN achieves superior performance on four real-world datasets from major online learning platforms.',
    pubType: 'preprint',
    citationCount: 9,
    isHighlight: false,
    status: 'published',
    source: 'agent',
    relatedMemberSlugs: ['zhu-taolin', 'fan-yizhou'],
    tags: ['Cognitive Diagnosis', 'Graph Neural Network', 'Knowledge Modeling'],
    createdAt: '2024-06-20',
  },
  {
    id: '6',
    title: 'Learning Analytics Dashboard Design: A User-Centered Framework for Teacher Decision Support',
    authors: ['Yizhou Fan', 'Luzhen Tang'],
    venue: 'Computers & Education',
    year: 2023,
    doi: '10.1016/j.compedu.2023.PLACEHOLDER',
    abstract:
      'Learning analytics dashboards (LADs) are increasingly deployed to help teachers monitor student progress. However, their design often fails to support teacher decision-making in practice. Drawing on interviews with 30 experienced teachers and a co-design process, we present a user-centered framework for LAD design that prioritizes actionability, interpretability, and contextual relevance. A field study with 12 classrooms shows significant improvements in teacher intervention frequency and quality.',
    pubType: 'journal',
    citationCount: 156,
    isHighlight: false,
    status: 'published',
    source: 'auto_crawler',
    relatedMemberSlugs: ['fan-yizhou', 'tang-luzhen'],
    tags: ['Learning Analytics', 'Dashboard', 'Teacher Support'],
    createdAt: '2023-04-01',
  },
  {
    id: '7',
    title: 'Can Large Language Models Serve as Effective Math Tutors? A Study on Socratic Questioning',
    authors: ['Mengyu Xia', 'Taolin Zhu', 'Yizhou Fan'],
    venue: 'EDM 2024',
    year: 2024,
    arxivId: '2407.00005',
    pdfUrl: 'https://arxiv.org/pdf/2407.00005',
    abstract:
      'Effective tutoring requires asking guiding questions rather than providing direct answers. We investigate whether large language models can engage in Socratic questioning for mathematics tutoring. Through a controlled experiment with 120 middle-school students, we find that LLM tutors employing Socratic dialogue lead to significantly better learning outcomes compared to direct answer models, but still fall short of expert human tutors in maintaining productive struggle.',
    pubType: 'conference',
    citationCount: 33,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['xia-mengyu', 'zhu-taolin', 'fan-yizhou'],
    tags: ['LLM Tutoring', 'Socratic Questioning', 'Math Education'],
    createdAt: '2024-07-05',
  },
  {
    id: 'real_zh_2025_human_ai_tutors',
    title: '人类导师与智能导师效能差异研究——基于动态交互的可供性视角',
    authors: ['李姗姗', '吴筱萌', '张鹏', '范逸洲'],
    venue: '开放教育研究 31(2)',
    year: 2025,
    doi: '10.13966/j.cnki.kfjyyj.2025.02.010',
    pdfUrl: 'https://openedu.sou.edu.cn/upload/qikanfile/202503280953157143.pdf',
    sourceUrl: 'https://doi.org/10.13966/j.cnki.kfjyyj.2025.02.010',
    language: 'zh',
    abstract:
      '研究从动态交互与可供性视角比较人类导师和智能导师的辅导效能，分析两类导师在学习支持方式与互动过程上的特点，为智能导师系统的设计与应用提供参考。',
    pubType: 'journal',
    citationCount: 0,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['fan-yizhou'],
    tags: ['智能导师', '人机交互', '教育人工智能'],
    createdAt: '2025-04-01',
  },
  {
    id: 'real_zh_2026_ai_literacy',
    title: '中小学生人工智能素养：内涵嬗变、目标升级与“3×3框架”建构',
    authors: ['汪滢', '李智迅', '汪琼', '范逸洲'],
    venue: '现代教育技术 36(3)',
    year: 2026,
    doi: '10.3969/j.issn.1009-8097.2026.03.009',
    sourceUrl: 'https://doi.org/10.3969/j.issn.1009-8097.2026.03.009',
    language: 'zh',
    abstract:
      '研究梳理中小学生人工智能素养内涵的变化，并围绕素养目标升级提出“3×3框架”，为学校人工智能教育的课程设计、教学实施与评价提供结构化参考。',
    pubType: 'journal',
    citationCount: 0,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['fan-yizhou'],
    tags: ['人工智能素养', '中小学教育', '素养框架'],
    createdAt: '2026-03-01',
  },
  {
    id: 'real_zh_2026_dialogue_irf',
    title: '从单线回应到协商共建：基于IRF理论的人机与师生对话分析',
    authors: ['冷静', '王章涵', '李思源', '范逸洲'],
    venue: '中国电化教育 2026(6)',
    year: 2026,
    sourceUrl: 'https://zdjy.cbpt.cnki.net/portal/journal/portal/client/paper/610338caec20d3752eb1aa3124941dbb',
    language: 'zh',
    abstract:
      '研究借助IRF理论比较人机对话与师生对话的互动结构，关注对话如何从单次问答走向协商与共同建构，为教育智能体的对话设计提供依据。',
    pubType: 'journal',
    citationCount: 0,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['fan-yizhou'],
    tags: ['人机对话', '师生互动', 'IRF理论'],
    createdAt: '2026-06-01',
  },
  {
    id: 'real_en_2026_flora',
    title: 'FLoRA: An advanced AI-powered engine to facilitate hybrid human-AI regulated learning',
    authors: ['Xinyu Li', 'Tongguang Li', 'Lixiang Yan', 'Yuheng Li', 'Linxuan Zhao', 'Mladen Raković', 'Inge Molenaar', 'Dragan Gašević', 'Yizhou Fan'],
    venue: 'Computers & Education 243, 105527',
    year: 2026,
    doi: '10.1016/j.compedu.2025.105527',
    arxivId: '2507.07362',
    pdfUrl: 'https://arxiv.org/pdf/2507.07362',
    sourceUrl: 'https://doi.org/10.1016/j.compedu.2025.105527',
    language: 'en',
    abstract:
      'FLoRA presents an AI-powered learning engine designed to support hybrid human–AI regulated learning by combining learner-facing support with traceable learning-process information and regulation mechanisms.',
    pubType: 'journal',
    citationCount: 0,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    // Xinyu Li is a Monash University researcher; do not associate this paper with the
    // newly added PKU master student until their identities have been verified.
    relatedMemberSlugs: ['fan-yizhou'],
    tags: ['Human-AI Learning', 'Self-Regulated Learning', 'Learning Analytics'],
    createdAt: '2026-01-01',
  },
  {
    id: 'real_en_2026_clinical_reasoning',
    title: 'Developing and Validating a Coding Scheme for Clinical Reasoning in History Taking Using Generative AI–Based Virtual Patients: Systematic Text Condensation Approach',
    authors: ['Naping Chen', 'Luzhen Tang', 'Yang Liu', 'Changmin Lin', 'Zijian Li', 'Chujun Shi', 'Mengyu Xia', 'Dragan Gasevic', 'Danijela Gasevic', 'Jinbin Zheng', 'Yizhou Fan', 'Xinyu Li'],
    venue: 'JMIR Medical Education 12, e84347',
    year: 2026,
    doi: '10.2196/84347',
    pdfUrl: 'https://mededu.jmir.org/2026/1/e84347/PDF',
    sourceUrl: 'https://mededu.jmir.org/2026/1/e84347',
    language: 'en',
    abstract:
      'The study develops and validates a coding scheme for analysing clinical reasoning during history-taking practice with generative AI–based virtual patients, providing a structured way to examine learners’ reasoning processes.',
    pubType: 'journal',
    citationCount: 0,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['tang-luzhen', 'xia-mengyu', 'fan-yizhou'],
    tags: ['Clinical Reasoning', 'Generative AI', 'Virtual Patient'],
    createdAt: '2026-04-13',
  },
  {
    id: 'real_en_2025_genai_metacognition',
    title: 'How GenAI affects metacognition in self-regulated learning: Between enhancement and inhibition',
    authors: ['Zijian Li', 'Yizhou Fan'],
    venue: 'Learning with Generative Artificial Intelligence (Taylor & Francis)',
    year: 2025,
    sourceUrl: 'https://www.taylorfrancis.com/books/oa-edit/9781003520699',
    language: 'en',
    abstract:
      'This chapter explores the impact of generative artificial intelligence (GenAI) on metacognition in self-regulated learning (SRL), examining both enhancement and inhibition effects.',
    pubType: 'book',
    citationCount: 6,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['li-zijian', 'fan-yizhou'],
    tags: ['GenAI', 'Metacognition', 'Self-Regulated Learning'],
    createdAt: '2025-06-01',
  },
  {
    id: 'real_en_2025_feedback_preference',
    title: "Breaking human dominance: Investigating learners' preferences for learning feedback from generative AI and human tutors",
    authors: ['H. Le', 'Y. Shen', 'Zijian Li', 'Mengyu Xia', 'L. Tang', 'X. Li', 'J. Jia', 'Q. Wang', 'D. Gašević', 'Yizhou Fan'],
    venue: 'British Journal of Educational Technology 56(5), 1758–1783',
    year: 2025,
    doi: '10.1111/bjet.13544',
    sourceUrl: 'https://doi.org/10.1111/bjet.13544',
    language: 'en',
    abstract:
      'This study investigates learners\' preferences for feedback from generative AI versus human tutors, addressing concerns about over-reliance and metacognitive laziness.',
    pubType: 'journal',
    citationCount: 34,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['li-zijian', 'xia-mengyu', 'fan-yizhou'],
    tags: ['GenAI Feedback', 'Learning Preferences', 'Human-AI'],
    createdAt: '2025-09-01',
  },
  {
    id: 'real_en_2026_llm_deductive_coding',
    title: 'When LLMs Fall Short in Deductive Coding: Model Comparisons and Human–AI Collaboration Workflow Design',
    authors: ['Zijian Li', 'L. Tang', 'Mengyu Xia', 'X. Li', 'N. Chen', 'D. Gašević', 'Yizhou Fan'],
    venue: 'Proceedings of LAK\'26: 16th International Learning Analytics and Knowledge Conference',
    year: 2026,
    language: 'en',
    abstract:
      'This paper investigates limitations of large language models in deductive coding tasks and proposes a human–AI collaboration workflow to improve coding accuracy.',
    pubType: 'conference',
    citationCount: 2,
    isHighlight: false,
    status: 'published',
    source: 'manual',
    relatedMemberSlugs: ['li-zijian', 'xia-mengyu', 'fan-yizhou'],
    tags: ['LLM', 'Deductive Coding', 'Learning Analytics'],
    createdAt: '2026-03-01',
  },
]

export const MOCK_NEWS: NewsItem[] = [
  {
    id: 'news_2026_new_members',
    title: '马玲、马郡阳加入课题组',
    summary: '欢迎马玲同学和马郡阳同学加入课题组。',
    content:
      '2026年5月20日，马玲同学和马郡阳同学加入课题组。马玲同学此前在华东师范大学学习，将于2026年9月入学攻读博士研究生；马郡阳同学是北京大学信息管理系本科生，将于2026年9月进入北京大学教育学院攻读硕士研究生。欢迎两位新成员！',
    category: 'member',
    memberSlug: 'ma-ling',
    relatedMemberSlugs: ['ma-ling', 'ma-junyang'],
    authorName: 'FanLearn Lab',
    eventDate: '2026-05-20',
    status: 'published',
    source: 'manual',
    createdAt: '2026-05-20',
  },
  {
    id: 'news_2026_fan_track_chair',
    title: '范逸洲老师担任学术会议子会议主席',
    summary: '范逸洲老师受邀担任相关学术会议子会议主席。',
    content:
      '2026年6月11日，范逸洲老师受邀担任相关学术会议子会议主席，参与会议学术议题组织与交流工作。具体会议信息请查看参考链接。',
    category: 'academic',
    memberSlug: 'fan-yizhou',
    relatedMemberSlugs: ['fan-yizhou'],
    authorName: 'FanLearn Lab',
    eventDate: '2026-06-11',
    referenceLinks: ['https://mp.weixin.qq.com/s/XA5eQBY4usjOIkToosdc_w'],
    status: 'published',
    source: 'manual',
    createdAt: '2026-06-11',
  },
  {
    id: 'news_2026_tang_graduation',
    title: '祝贺唐陆禛同学顺利毕业',
    summary: '北京大学教育学院举行2026年毕业典礼，祝贺唐陆禛同学顺利毕业。',
    content:
      '2026年7月6日，北京大学教育学院举行毕业典礼。祝贺唐陆禛同学顺利完成学业、圆满毕业，祝愿她在未来继续保持热爱、不断成长。',
    category: 'member',
    memberSlug: 'tang-luzhen',
    relatedMemberSlugs: ['tang-luzhen'],
    authorName: 'FanLearn Lab',
    eventDate: '2026-07-06',
    referenceLinks: ['https://mp.weixin.qq.com/s/bYpS12RwBqh2NP9ZHijjAg'],
    status: 'published',
    source: 'manual',
    createdAt: '2026-07-06',
  },
  {
    id: 'news_2025_human_ai_tutors',
    title: '课题组论文发表于《开放教育研究》',
    summary: '课题组关于人类导师与智能导师效能差异的研究正式发表。',
    content:
      '2025年，李姗姗、吴筱萌、张鹏、范逸洲合作完成的论文《人类导师与智能导师效能差异研究——基于动态交互的可供性视角》发表于《开放教育研究》2025年第2期。研究比较了人类导师与智能导师在动态交互中的不同特点。',
    category: 'paper',
    memberSlug: 'fan-yizhou',
    relatedMemberSlugs: ['fan-yizhou'],
    authorName: 'FanLearn Lab',
    eventDate: '2025-04-01',
    referenceLinks: ['https://openedu.sou.edu.cn/upload/qikanfile/202503280953157143.pdf'],
    status: 'published',
    source: 'manual',
    createdAt: '2025-04-01',
  },
  {
    id: 'news_2026_clinical_reasoning',
    title: '课题组合作论文发表于 JMIR Medical Education',
    summary: '课题组合作研究提出并验证了生成式AI虚拟病人场景中的临床推理编码方案。',
    content:
      '2026年，唐陆禛、夏梦雨、范逸洲等作者参与的合作论文发表于 JMIR Medical Education。研究面向生成式AI虚拟病人支持的问诊练习，提出并验证了用于分析学习者临床推理过程的编码方案。',
    category: 'paper',
    memberSlug: 'fan-yizhou',
    relatedMemberSlugs: ['tang-luzhen', 'xia-mengyu', 'fan-yizhou'],
    authorName: 'FanLearn Lab',
    eventDate: '2026-04-13',
    referenceLinks: ['https://mededu.jmir.org/2026/1/e84347'],
    status: 'published',
    source: 'manual',
    createdAt: '2026-04-13',
  },
]
